# Development docker-compose for local development
version: '3.8'

services:
  # Redis for job queue and caching
  redis:
    image: redis:7.2-alpine
    container_name: grinn-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # Mock gRINN container for testing
  grinn-mock:
    image: python:3.10-slim
    container_name: grinn-mock
    volumes:
      - ../grinn:/app/grinn:ro
    working_dir: /app
    command: ["sleep", "infinity"]
    restart: unless-stopped

volumes:
  redis_dev_data:
    driver: local

networks:
  default:
    name: grinn-dev-network